vm_box: "ubuntu/bionic64"
docker_version: 18.09.9
master:
  cpus: 2
  memory: 2048
ip:
  master: 10.0.0.10
keys:
  public_key: "../ssh/id_rsa.pub"
  private_key: "../ssh/id_rsa"
network:
  network_type: private_network
